use std::error::Error;

type AppResult = Result<(), Box<dyn Error>>;

fn main() -> AppResult {
    Ok(())
}
